title: Learning to use GitHub
author: doreahardy
email: info@door-a-designs.com
description: > # this means to ignore newlines until "baseurl:"
  I'm learning to use GitHub ...because... well... it's something good 
  to know. Also because, I love learning. And well... because I write
  code ... and I want to learn to share that code!

# social links
twitter_username: dooradesigns
github_username:  doreahardy

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
